white-minnow:
  fhir-client:
    url: https://msdemo-livetest-api.medicasoft.us:8443/fhir

logging:
  level:
    reactor:
      netty:
        http:
          client: debug

spring.config.import: >
  nxt-key.yml,
  nxt-crt.yml
